# Generated by Django 3.2.8 on 2021-10-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateTimeField(verbose_name='시작날짜')),
                ('end_day', models.DateTimeField(verbose_name='종료날짜')),
                ('company', models.CharField(max_length=128, verbose_name='업체명')),
                ('position', models.CharField(max_length=128, verbose_name='직책')),
                ('guest_name', models.CharField(max_length=32, verbose_name='출입자명')),
            ],
            options={
                'verbose_name': '출입명단',
                'verbose_name_plural': '출입명단',
                'db_table': 'board',
            },
        ),
    ]
